sudo: required
dist: trusty

services:
  - docker

install:
  # Install docker engine from Docker's Ubuntu repo
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb https://download.docker.com/linux/ubuntu trusty stable"
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --assume-yes install docker-ce
  - docker version

  # Update docker-compose via pip
  - sudo pip install docker-compose
  - docker-compose version

before_script:
  - docker-compose up --build -d

script:
  - ./test.sh

after_script:
  - docker-compose down

after_failure:
  - docker logs sabnzbd

after_success:
  - docker history dockersabnzbd_sabnzbd
